import 'mapbox-gl/dist/mapbox-gl.css';

import { Inter } from 'next/font/google';
import Providers from '@/app/providers';
import Header from '@/components/header';
import './globals.css';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${inter.className} bg-white`}>
          <div className="flex h-screen w-full flex-col">
            <Header />
            <div className="flex-1 overflow-hidden">{children}</div>
          </div>
        </body>
      </html>
    </Providers>
  );
}
